import type { Metadata } from "next";
import { Navigation } from "@/components/organisms/layout/header/navigation";
import { Footer } from "@/components/organisms/layout/footer/footer";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { DisableDraftMode } from "@/components/molecules/presentation/disableDraftMode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDraftMode = (await draftMode()).isEnabled;
  return (
    <>
      <Navigation />
      <main>
        {children}
        <SanityLive />
        {isDraftMode && (
          <>
            <VisualEditing />
            <DisableDraftMode />
          </>
        )}
      </main>
      <Footer />
    </>
  );
}
